apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unifi-poller.fullname" . }}
  labels:
    {{- include "unifi-poller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "unifi-poller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "unifi-poller.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port.http }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Release.Name }}-settings
              mountPath: /etc/unifi-poller/
              subPath: up.conf
      volumes:
        - name: {{ .Release.Name }}-settings
          configMap:
            name: {{ .Release.Name }}-settings
            items:
              - key: up.conf
                path: up.conf
