{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "unifi-poller.fullname" . }}
  labels:
    {{- include "unifi-poller.labels" . | nindent 4 }}
    {{- with .Values.prometheus.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
    {{- include "unifi-poller.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    {{- with .Values.prometheus.serviceMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    path: /metrics
{{- end }}
