replicaCount: 1

image:
  repository: habakke/hmq
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: LoadBalancer
  port:
    mqtt: 1883
    http: 8080
  name: mqtt

serviceMonitor:
  enabled: true
  interval: "1m"
  scrapeTimeout: 5s
  # namespace: default
  additionalLabels: {}
